# Generated by Django 3.2 on 2021-04-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_data_coke'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coke',
            new_name='data',
        ),
    ]
